Restore `IO_REG_TYPE` definition for AVR
The definition of the `IO_REG_TYPE` macro when compiling for an AVR target was accidentally removed by the previous
commit. This resulted in the library failing to compile for those targets:

```
Encoder.h:66:11: error: 'IO_REG_TYPE' does not name a type
  volatile IO_REG_TYPE * pin1_register;
           ^~~~~~~~~~~
```

The macro definition is hereby restored.